language: php

php:
  - 7.4
  - nightly

# matrix:
#   allow_failures:
#     - php: nightly

cache:
  apt: true
  bundler: true

install:
  travis_retry composer install --no-interaction --prefer-source

script: composer app:test
